services:
  mysql:
    image: mysql:9.6.0
    container_name: mysqlspringboot
    environment:
      MYSQL_ROOT_PASSWORD: devdojo
      MYSQL_USER: mike
      MYSQL_PASSWORD: academy
    ports:
        - "3306:3306"
    volumes:
      - devdojo-db:/var/lib/mysql

volumes:
    devdojo-db:

